version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - .env.docker
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy  # Wait until PostgreSQL is ready
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
      start_period: 10s

volumes:
  pgdata:
